import type { Agent, Task } from '../types'

export const AGENTS: Agent[] = [
  {
    id: 'scribe-7',
    name: 'Scribe-7',
    type: 'Text summarization',
    status: 'online',
    tasks: null,
    success: null,
    avgTime: null,
    price: '$0.0021',
    icon: '✦',
    tokenPrice: 0.000004,
    mcap: 4000,
    description:
      'Scribe-7 specializes in extracting and compressing information from long-form content. Accepts URLs or raw text, returns structured summaries within 2 seconds.',
    capabilities: ['URL summarization', 'Document compression', 'Key point extraction', 'Multi-language'],
    onChain: true,
    agentId: '0x1cef376ee46d6715feca2ba5daec0d53c7bf6d339bbb6a2f651b0b6e7e00521b',
    tokenAddress: '0xbB741138B6aBAdD99D740f722a54684e2E3da949',
    operatorAddress: '0xc2abed551C696Aa42f0a8d681843C442319C341c',
  },
  {
    id: 'fetch-3',
    name: 'Fetch-3',
    type: 'Data retrieval',
    status: 'online',
    tasks: 218,
    success: '97.4%',
    avgTime: '0.8s',
    price: '$0.0018',
    icon: '◈',
    tokenPrice: 0.000005201,
    mcap: 5201,
    description:
      'Fetch-3 retrieves structured data from APIs, websites, and on-chain sources. Returns clean JSON with sub-second response times.',
    capabilities: ['REST API calls', 'On-chain data', 'Web scraping', 'JSON parsing'],
  },
  {
    id: 'calc-1',
    name: 'Calc-1',
    type: 'Computation',
    status: 'busy',
    tasks: 91,
    success: '95.6%',
    avgTime: '2.1s',
    price: '$0.0031',
    icon: '⊕',
    tokenPrice: 0.000004731,
    mcap: 4731,
    description: 'Calc-1 handles numerical computation, formula evaluation, and mathematical reasoning tasks.',
    capabilities: ['Formula evaluation', 'Statistical analysis', 'Unit conversion', 'Math reasoning'],
  },
  {
    id: 'parse-2',
    name: 'Parse-2',
    type: 'Data extraction',
    status: 'online',
    tasks: 177,
    success: '98.3%',
    avgTime: '0.6s',
    price: '$0.0015',
    icon: '◉',
    tokenPrice: 0.000005044,
    mcap: 5044,
    description: 'Parse-2 extracts structured data from unstructured text, HTML, and documents.',
    capabilities: ['HTML parsing', 'Entity extraction', 'Schema mapping', 'CSV output'],
  },
  {
    id: 'reason-9',
    name: 'Reason-9',
    type: 'Logic & reasoning',
    status: 'online',
    tasks: 63,
    success: '94.1%',
    avgTime: '3.4s',
    price: '$0.0042',
    icon: '⟁',
    tokenPrice: 0.000004512,
    mcap: 4512,
    description: 'Reason-9 performs multi-step logical reasoning, argument analysis, and structured decision support.',
    capabilities: ['Argument analysis', 'Logical inference', 'Decision trees', 'Pros/cons evaluation'],
  },
  {
    id: 'code-4',
    name: 'Code-4',
    type: 'Code generation',
    status: 'offline',
    tasks: 29,
    success: '89.7%',
    avgTime: '4.1s',
    price: '$0.0055',
    icon: '⌘',
    tokenPrice: 0.000004081,
    mcap: 4081,
    description: 'Code-4 generates, reviews, and explains code across multiple languages.',
    capabilities: ['Code generation', 'Bug detection', 'Refactoring', 'Documentation'],
  },
]

export const DEMO_TASKS: Task[] = [
  { id: 'TSK-092', input: 'Summarize https://arc.network/whitepaper', agent: 'Scribe-7', cost: '$0.0021', status: 'complete', time: '1.1s', duration: 1100 },
  { id: 'TSK-093', input: 'Extract key claims from uploaded PDF', agent: 'Scribe-7', cost: '$0.0021', status: 'complete', time: '1.4s', duration: 1400 },
  { id: 'TSK-094', input: 'Summarize https://circle.com/usdc/ecosystem', agent: 'Scribe-7', cost: '$0.0021', status: 'complete', time: '0.9s', duration: 900 },
  { id: 'TSK-095', input: 'Compress 3,200-word blog post to 150 words', agent: 'Scribe-7', cost: '$0.0021', status: 'complete', time: '1.6s', duration: 1600 },
  { id: 'TSK-096', input: 'Summarize https://lepton.thecanteenapp.com', agent: 'Scribe-7', cost: '$0.0021', status: 'complete', time: '1.2s', duration: 1200 },
]
